# Конфигурация путей
paths:
  base_dir: ".."
  data_dir: "data"
  test_dir: "test_dir"
  archive_file: "test_archive"
  extract_dir: "extracted"
  perf_archive_dir: "perf_archives"

# Конфигурация архива
archive:
  type: 7z

# Обычные тестовые файлы
test_files:
  - path: "file1.txt"
    content: "Содержимое файла 1"
    type: "text"

  - path: "file2.txt"
    content: "Содержимое файла 2"
    type: "text"

  - path: "binary.dat"
    content: "00010203FF"
    type: "binary"

  - path: "subdir/file3.txt"
    content: "Файл в поддиректории"
    type: "text"

  - path: "empty_file.txt"
    content: ""
    type: "binary"

# Параметры для теста производительности
performance:
  block_size: "1M"  # Размер блока для dd
  test_cases:
    # Одиночные файлы разных размеров
    - name: "Single 1MB"
      file_sizes: [1]
      file_count: 1
      total_size: 1

    - name: "Single 2MB"
      file_sizes: [2]
      file_count: 1
      total_size: 2

    - name: "Single 5MB"
      file_sizes: [5]
      file_count: 1
      total_size: 5

    - name: "Single 10MB"
      file_sizes: [10]
      file_count: 1
      total_size: 10

    # Наборы файлов для сравнения
    - name: "5 files × 2MB"
      file_sizes: [2, 2, 2, 2, 2]
      file_count: 5
      total_size: 10

    - name: "2 files × 5MB"
      file_sizes: [5, 5]
      file_count: 2
      total_size: 10

    # Дополнительные тесты
    - name: "Mixed sizes"
      file_sizes: [1, 3, 6]
      file_count: 3
      total_size: 10